# Generated by Django 4.0.3 on 2022-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
