# Generated by Django 4.0.3 on 2022-05-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_okuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okuser',
            options={'ordering': ('id', 'first_name')},
        ),
        migrations.RemoveField(
            model_name='okuser',
            name='is_staff',
        ),
    ]
