# Generated by Django 4.0.3 on 2022-05-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_okuser_options_remove_okuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='okuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
